### ISSUE TITLE
Using too much memory (~450MB) on MacOS

### ISSUE THREAD

**Issue by damywise** [freethinkel/toolboard#2]
I noticed that it's using ~450MB memory on my MacOS 12.3, might be a memory leak issue?

**Comment by freethinkel** [comment]
Yes, most likely a memory leak, I'll try to figure it out. Thanks

**Comment by freethinkel** [comment]
I wrote a [new version](https://github.com/freethinkel/toolbox), there this problem should be solved

**Comment by damywise** [comment]
memory leak fixed but window manager no longer works. The size/snap shows but the app doesn't resize
